# Generated by Django 5.2.3 on 2025-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('best_of', models.IntegerField(default=3)),
                ('set_player1', models.IntegerField(default=0)),
                ('set_player2', models.IntegerField(default=0)),
                ('game_player1', models.IntegerField(default=0)),
                ('game_player2', models.IntegerField(default=0)),
                ('point_player1', models.IntegerField(default=0)),
                ('point_player2', models.IntegerField(default=0)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
