# Generated by Django 5.2.3 on 2025-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_of',
            field=models.PositiveIntegerField(choices=[(3, 'Best of 3'), (5, 'Best of 5')], default=3),
        ),
    ]
