# Generated by Django 5.2.3 on 2025-06-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_invitedplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
